"""Vendor the official v1.3.9 dynamic subsets; never subset blog content.

python scripts/sync-pretendard.py --download
python scripts/sync-pretendard.py --verify [--fonttools-path /path/to/packages]
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
import re
import sys
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "public/font"
DEST = FONT / "pretendard-1.3.9"
BASE = "https://raw.githubusercontent.com/orioncactus/pretendard/v1.3.9/"
CSS_PATH = "dist/web/variable/pretendardvariable-dynamic-subset.css"
MANIFEST = DEST / "manifest.json"
ORIGINAL_SHA256 = "9599f12fd42fc0bce1cd50b47a0c022e108d7aa64dd0d1bb0ed44f3282d900b4"


def digest(data):
    return hashlib.sha256(data).hexdigest()


def ranges(text):
    result = set()
    for token in text.split(","):
        bounds = token.strip().removeprefix("U+").split("-")
        low = int(bounds[0], 16)
        high = int(bounds[-1], 16)
        result.update(range(low, high + 1))
    return result


def compact_ranges(codepoints):
    groups = []
    for point in sorted(codepoints):
        if groups and point == groups[-1][1] + 1:
            groups[-1][1] = point
        else:
            groups.append([point, point])
    return ", ".join(f"U+{low:X}" if low == high else f"U+{low:X}-{high:X}" for low, high in groups)


def download():
    old = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else None

    def fetch(path):
        with urlopen(BASE + path, timeout=60) as response:
            data = response.read()
        if old and old["upstream_sha256"].get(path) != digest(data):
            raise ValueError(f"Upstream asset changed: {path}")
        return path, data

    _, css_data = fetch(CSS_PATH)
    css = css_data.decode("utf-8")
    paths = re.findall(r"url\(\.\./\.\./\.\./([^\)]+)\)", css)
    with ThreadPoolExecutor(max_workers=8) as pool:
        downloads = dict(pool.map(fetch, paths + ["LICENSE"]))
    downloads[CSS_PATH] = css_data
    DEST.mkdir(parents=True, exist_ok=True)
    for path in paths:
        (DEST / Path(path).name).write_bytes(downloads[path])
    (DEST / "upstream.css").write_bytes(css_data)
    (FONT / "OFL.txt").write_bytes(downloads["LICENSE"])
    manifest = {
        "version": "1.3.9",
        "source": BASE,
        "original_sha256": ORIGINAL_SHA256,
        "upstream_sha256": {path: digest(data) for path, data in sorted(downloads.items())},
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"Vendored {len(paths)} official subsets without modifying font binaries.")


def generate():
    from fontTools.ttLib import TTFont
    css = (DEST / "upstream.css").read_text(encoding="utf-8")
    css = css.replace("'Pretendard Variable'", '"Pretendard"')
    css = re.sub(r"url\(\.\./\.\./\.\./([^\)]+)\)",
                 lambda m: 'url("/font/pretendard-1.3.9/' + Path(m[1]).name + '")', css)
    covered = set()
    for unicode_range in re.findall(r"unicode-range:\s*([^;]+);", css):
        covered.update(ranges(unicode_range))
    missing = set(TTFont(FONT / "PretendardVariable.woff2").getBestCmap()) - covered
    css += '\n// Preserve original characters omitted by the official dynamic subsets.\n'
    css += '@font-face {\n  font-family: "Pretendard";\n  font-style: normal;\n'
    css += '  font-display: swap;\n  font-weight: 45 920;\n'
    css += '  src: url("/font/PretendardVariable.woff2") format("woff2-variations");\n'
    css += '  unicode-range: ' + compact_ranges(missing) + ';\n}\n'
    (ROOT / "src/styles/font.scss").write_text(
        "// Generated by scripts/sync-pretendard.py from official v1.3.9 assets.\n" + css,
        encoding="utf-8", newline="\n")
    print(f"Generated CSS with conditional original-font fallback for {len(missing)} codepoints.")


def verify():
    from fontTools.ttLib import TTFont
    manifest = json.loads(MANIFEST.read_text())
    original_path = FONT / "PretendardVariable.woff2"
    assert digest(original_path.read_bytes()) == ORIGINAL_SHA256
    original = TTFont(original_path)
    expected = set(original.getBestCmap())
    union = set()
    css = (ROOT / "src/styles/font.scss").read_text(encoding="utf-8")
    fonts = re.findall(r'url\("/font/pretendard-1\.3\.9/([^\"]+)"\).*?unicode-range:\s*([^;]+);', css, re.S)
    total = 0
    for name, unicode_range in fonts:
        path = DEST / name
        data = path.read_bytes()
        upstream_path = "packages/pretendard/dist/web/variable/woff2-dynamic-subset/" + name
        assert digest(data) == manifest["upstream_sha256"][upstream_path], name
        font = TTFont(path)
        mapped = set(font.getBestCmap())
        declared = ranges(unicode_range)
        union.update(mapped & declared)
        assert [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in font["fvar"].axes] == [
            (a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in original["fvar"].axes], name
        total += len(data)
    fallback = re.search(r'url\("/font/PretendardVariable.woff2"\).*?unicode-range:\s*([^;]+);', css, re.S)
    assert fallback, "Full-coverage fallback missing"
    fallback_points = ranges(fallback[1])
    assert not (fallback_points & union), "Fallback overlaps dynamic subset characters"
    missing = expected - (union | (fallback_points & expected))
    assert not missing, f"Missing {len(missing)} original codepoints"
    assert digest((FONT / "OFL.txt").read_bytes()) == manifest["upstream_sha256"]["LICENSE"]
    print(f"Verified {len(fonts)} official files, {len(expected)} original codepoints, variable axes, license and SHA256 checksums.")
    print(f"All chunks total {total:,} bytes; browsers request only matching unicode ranges.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--download", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--fonttools-path")
    args = parser.parse_args()
    if args.fonttools_path:
        sys.path.insert(0, args.fonttools_path)
    if args.download:
        download()
    if args.download or args.generate:
        generate()
    if args.verify:
        verify()
    if not (args.download or args.generate or args.verify):
        parser.print_help()
